language: csharp
solution: ./homework\ 3/SimpleFTP/SimpleFTP.sln

git:
  depth: 1

mono: none
dotnet: 2.1

branches:
  only:
    - hw_3/SimpleFTP

  
matrix:
  include:
    - script:
      - cd ./homework\ 3/SimpleFTP && dotnet restore && dotnet build
    - script:
      - dotnet test ./homework\ 3/SimpleFTP/SimpleFTPClient/ClientTests
    - script:
      - dotnet test ./homework\ 3/SimpleFTP/SimpleFTPServer/ServerTests

